### ISSUE TITLE
Does preloadPagesCount cover the previous pages symetrically?

### ISSUE THREAD

**Issue by aytunch** [octomato/preload_page_view#8]
It is often that we display a PageView which starts from the middle page instead of start(page zero).

Let's say there are 30 Pages and we display Page 15 at the moment. If preloadPagesCount is 3, I should expect to preload pages 14,15 and 16. Because we don't know if the user will swipe right or left initally.

If you don't want to make a breaking change, we can add an optional field called "notSymetric" and it would default to true. if we set it to false, it would work as I described above.

**Comment by octomato** [comment]
Hey @aytunch , thanks for your feedback. Not sure but personally I think the widget should symetrically by default, it will bring some confusing to other developer if it's not symetrically.

For my perceptive, we can not control user's behavior, if we display page 15, the user could swipe down and swipe up, symetrically preload still reasonable.

Close this ticket because personally I don't think it's a valid scenario. Please feel free to create a new ticket if you find reasonable scenario.
